IPv6 host cloaking (ugly, but works)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12409,7 +12409,9 @@ fi
 
 
 
-for ac_func in index strerror strtoken strtok inet_addr inet_ntoa inet_netof inet_aton
+
+
+for ac_func in index strerror strtoken strtok inet_addr inet_ntoa inet_netof inet_aton inet_ntop inet_pton
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -13534,6 +13536,69 @@ presetting ac_cv_c_bigendian=no (or yes) will help" >&2;}
    { (exit 1); exit 1; }; } ;;
 esac
 
+
+echo "$as_me:$LINENO: checking for basic IPv6 support" >&5
+echo $ECHO_N "checking for basic IPv6 support... $ECHO_C" >&6
+if test "${baha_cv_ipv6_support+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <sys/types.h>
+#include <sys/socket.h>
+#include <netinet/in.h>
+int
+main ()
+{
+struct sockaddr_in6 s; struct in6_addr t=in6addr_any; int i=AF_INET6; t.s6_addr[0] = 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  baha_cv_ipv6_support=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+baha_cv_ipv6_support=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $baha_cv_ipv6_support" >&5
+echo "${ECHO_T}$baha_cv_ipv6_support" >&6
+
+if test "$baha_cv_ipv6_support" = no; then
+  { { echo "$as_me:$LINENO: error: Sorry, your C library apparently lacks support for AF_INET6 and I do not like this." >&5
+echo "$as_me: error: Sorry, your C library apparently lacks support for AF_INET6 and I do not like this." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 tryzlib=""
